array_width = 64
attr_fn_like_width = 64
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 0
brace_style = "SameLineWhere"
chain_width = 64
color = "Auto"
combine_control_expr = true
comment_width = 96
condense_wildcard_suffixes = false
control_brace_style = "ClosingNextLine"
disable_all_formatting = false
doc_comment_code_block_width = 100
edition = "2021"
emit_mode = "Files"
empty_item_single_line = true
enum_discrim_align_threshold = 32
error_on_line_overflow = false
error_on_unformatted = false
fn_call_width = 64
fn_params_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = false
group_imports = "Preserve"
hard_tabs = false
hex_literal_case = "Lower"
hide_parse_errors = false
ignore = []
imports_granularity = "Preserve"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
make_backup = false
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 128
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = false
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
required_version = "1.5.2"
short_array_element_width_threshold = 10
single_line_if_else_max_width = 64
skip_children = false
skip_macro_invocations = []
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 32
struct_lit_single_line = true
struct_lit_width = 18
struct_variant_width = 32
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = false
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
version = "One"
where_single_line = false
wrap_comments = true
